### ISSUE TITLE
Filter overrides registered public methods as non public: h

### ISSUE THREAD

**Issue by richpeck** [chamnap/liquid-rails#24]
`Rails 5.0.0`, `Liquid 4.0.0rc2` --

![untitled-1](https://cloud.githubusercontent.com/assets/1104431/16894299/1bd386ee-4b4a-11e6-8f15-992aea5ecdc9.jpg)

```
C:/Dev/Dependencies/Ruby/ruby-2.3.0-x64-mingw32/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'liquid-rails'. (Bundler::GemRequireError)
Gem Load Error is: Liquid error: Filter overrides registered public methods as non public: h
```

Any advice?

**Comment by chamnap** [comment]
This gem doesn't support rails 5 and latest liquid yet.

**Comment by rafaelgaspar** [comment]
This is also happening on rails 4.x now that liquid 4.0.0 was released.

Need to change https://github.com/chamnap/liquid-rails/blob/master/liquid-rails.gemspec#L24 to ~> 3.0.

**Comment by brandoncordell** [comment]
I created a pull request for this: #30

**Comment by Robert-Christopher** [comment]
@chamnap Will you be merging the PR by @brandoncordell anytime soon ?
