### ISSUE TITLE
Liquid-Rails sets content-type to text/html during non-HTML rendering

### ISSUE THREAD

**Issue by inopinatus** [chamnap/liquid-rails#26]
I've just found that some of my liquid-templated outbound email is being junked, and the root cause is because Liquid::Rails::TemplateHandler#render sets the Content-Type for the entire view to text/html, which overrides the multipart/alternative that ActionMailer would normally use.

As a result, services like Hotmail, Gmail perceive an HTML-only message and this raises the spam score.

Any particular reason why this is so? After all liquid templates are generic, they're not just HTML, so it's a false assumption.

I've also just tested using a .liquid partial in a .text.erb template and found that this too incorrectly turns a text/plain response into text/html response. So this something that could change browser behaviour.

**Comment by GimliLongBow** [comment]
Ran into this same issue earlier this year for RSS feeds: https://github.com/chamnap/liquid-rails/pull/17
